//! The compile-time engine/command registry, generated by `build.rs` from
//! `config.json`. All command registration and engine knowledge in this CLI
//! flows from these statics — see `spec.rs` for the types and `config.json`
//! (workspace root) for the source of truth.

include!(concat!(env!("OUT_DIR"), "/engines_gen.rs"));
