//! Canonical Dalvik opcode table: name + instruction format (length class).

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Fmt {
    None, // unassigned
    F10x,
    F12x,
    F11n,
    F11x,
    F10t,
    F20t,
    F22x,
    F32x,
    F21t,
    F21s,
    F21h,
    F21c,
    F23x,
    F22b,
    F22t,
    F22s,
    F22c,
    F30t,
    F31i,
    F31t,
    F31c,
    F35c,
    F3rc,
    F45cc,
    F4rcc,
    F51l,
    Payload,
}

/// code units per format
pub fn fmt_len(f: Fmt) -> usize {
    match f {
        Fmt::F10x | Fmt::F12x | Fmt::F11n | Fmt::F11x | Fmt::F10t | Fmt::None => 1,
        Fmt::F20t
        | Fmt::F22x
        | Fmt::F21t
        | Fmt::F21s
        | Fmt::F21h
        | Fmt::F21c
        | Fmt::F23x
        | Fmt::F22b
        | Fmt::F22t
        | Fmt::F22s
        | Fmt::F22c => 2,
        Fmt::F30t | Fmt::F31i | Fmt::F31t | Fmt::F31c | Fmt::F35c | Fmt::F3rc | Fmt::F32x => 3,
        Fmt::F45cc | Fmt::F4rcc => 4,
        Fmt::F51l => 5,
        Fmt::Payload => 0, // caller handles
    }
}

/// (name, format) for every opcode byte 0x00..=0xff.
pub static OPCODES: [(&str, Fmt); 256] = [
    ("nop", Fmt::F10x),
    ("move", Fmt::F12x),
    ("move/from16", Fmt::F22x),
    ("move/16", Fmt::F32x),
    ("move-wide", Fmt::F12x),
    ("move-wide/from16", Fmt::F22x),
    ("move-wide/16", Fmt::F32x),
    ("move-object", Fmt::F12x),
    ("move-object/from16", Fmt::F22x),
    ("move-object/16", Fmt::F32x),
    ("move-result", Fmt::F11x),
    ("move-result-wide", Fmt::F11x),
    ("move-result-object", Fmt::F11x),
    ("move-exception", Fmt::F11x),
    ("return-void", Fmt::F10x),
    ("return", Fmt::F11x),
    ("return-wide", Fmt::F11x),
    ("return-object", Fmt::F11x),
    ("const/4", Fmt::F11n),
    ("const/16", Fmt::F21s),
    ("const", Fmt::F31i),
    ("const/high16", Fmt::F21h),
    ("const-wide/16", Fmt::F21s),
    ("const-wide/32", Fmt::F31i),
    ("const-wide", Fmt::F51l),
    ("const-wide/high16", Fmt::F21h),
    ("const-string", Fmt::F21c),
    ("const-string/jumbo", Fmt::F31c),
    ("const-class", Fmt::F21c),
    ("monitor-enter", Fmt::F11x),
    ("monitor-exit", Fmt::F11x),
    ("check-cast", Fmt::F21c),
    ("instance-of", Fmt::F22c),
    ("array-length", Fmt::F12x),
    ("new-instance", Fmt::F21c),
    ("new-array", Fmt::F22c),
    ("filled-new-array", Fmt::F35c),
    ("filled-new-array/range", Fmt::F3rc),
    ("fill-array-data", Fmt::F31t),
    ("throw", Fmt::F11x),
    ("goto", Fmt::F10t),
    ("goto/16", Fmt::F20t),
    ("goto/32", Fmt::F30t),
    ("packed-switch", Fmt::F31t),
    ("sparse-switch", Fmt::F31t),
    ("cmpl-float", Fmt::F23x),
    ("cmpg-float", Fmt::F23x),
    ("cmpl-double", Fmt::F23x),
    ("cmpg-double", Fmt::F23x),
    ("cmp-long", Fmt::F23x),
    ("if-eq", Fmt::F22t),
    ("if-ne", Fmt::F22t),
    ("if-lt", Fmt::F22t),
    ("if-ge", Fmt::F22t),
    ("if-gt", Fmt::F22t),
    ("if-le", Fmt::F22t),
    ("if-eqz", Fmt::F21t),
    ("if-nez", Fmt::F21t),
    ("if-ltz", Fmt::F21t),
    ("if-gez", Fmt::F21t),
    ("if-gtz", Fmt::F21t),
    ("if-lez", Fmt::F21t),
    ("unused-3e", Fmt::None),
    ("unused-3f", Fmt::None),
    ("unused-40", Fmt::None),
    ("unused-41", Fmt::None),
    ("unused-42", Fmt::None),
    ("unused-43", Fmt::None),
    ("aget", Fmt::F23x),
    ("aget-wide", Fmt::F23x),
    ("aget-object", Fmt::F23x),
    ("aget-boolean", Fmt::F23x),
    ("aget-byte", Fmt::F23x),
    ("aget-char", Fmt::F23x),
    ("aget-short", Fmt::F23x),
    ("aput", Fmt::F23x),
    ("aput-wide", Fmt::F23x),
    ("aput-object", Fmt::F23x),
    ("aput-boolean", Fmt::F23x),
    ("aput-byte", Fmt::F23x),
    ("aput-char", Fmt::F23x),
    ("aput-short", Fmt::F23x),
    ("iget", Fmt::F22c),
    ("iget-wide", Fmt::F22c),
    ("iget-object", Fmt::F22c),
    ("iget-boolean", Fmt::F22c),
    ("iget-byte", Fmt::F22c),
    ("iget-char", Fmt::F22c),
    ("iget-short", Fmt::F22c),
    ("iput", Fmt::F22c),
    ("iput-wide", Fmt::F22c),
    ("iput-object", Fmt::F22c),
    ("iput-boolean", Fmt::F22c),
    ("iput-byte", Fmt::F22c),
    ("iput-char", Fmt::F22c),
    ("iput-short", Fmt::F22c),
    ("sget", Fmt::F21c),
    ("sget-wide", Fmt::F21c),
    ("sget-object", Fmt::F21c),
    ("sget-boolean", Fmt::F21c),
    ("sget-byte", Fmt::F21c),
    ("sget-char", Fmt::F21c),
    ("sget-short", Fmt::F21c),
    ("sput", Fmt::F21c),
    ("sput-wide", Fmt::F21c),
    ("sput-object", Fmt::F21c),
    ("sput-boolean", Fmt::F21c),
    ("sput-byte", Fmt::F21c),
    ("sput-char", Fmt::F21c),
    ("sput-short", Fmt::F21c),
    ("invoke-virtual", Fmt::F35c),
    ("invoke-super", Fmt::F35c),
    ("invoke-direct", Fmt::F35c),
    ("invoke-static", Fmt::F35c),
    ("invoke-interface", Fmt::F35c),
    ("unused-73", Fmt::None),
    ("invoke-virtual/range", Fmt::F3rc),
    ("invoke-super/range", Fmt::F3rc),
    ("invoke-direct/range", Fmt::F3rc),
    ("invoke-static/range", Fmt::F3rc),
    ("invoke-interface/range", Fmt::F3rc),
    ("unused-79", Fmt::None),
    ("unused-7a", Fmt::None),
    ("neg-int", Fmt::F12x),
    ("not-int", Fmt::F12x),
    ("neg-long", Fmt::F12x),
    ("not-long", Fmt::F12x),
    ("neg-float", Fmt::F12x),
    ("neg-double", Fmt::F12x),
    ("int-to-long", Fmt::F12x),
    ("int-to-float", Fmt::F12x),
    ("int-to-double", Fmt::F12x),
    ("long-to-int", Fmt::F12x),
    ("long-to-float", Fmt::F12x),
    ("long-to-double", Fmt::F12x),
    ("float-to-int", Fmt::F12x),
    ("float-to-long", Fmt::F12x),
    ("float-to-double", Fmt::F12x),
    ("double-to-int", Fmt::F12x),
    ("double-to-long", Fmt::F12x),
    ("double-to-float", Fmt::F12x),
    ("int-to-byte", Fmt::F12x),
    ("int-to-char", Fmt::F12x),
    ("int-to-short", Fmt::F12x),
    ("add-int", Fmt::F23x),
    ("sub-int", Fmt::F23x),
    ("mul-int", Fmt::F23x),
    ("div-int", Fmt::F23x),
    ("rem-int", Fmt::F23x),
    ("and-int", Fmt::F23x),
    ("or-int", Fmt::F23x),
    ("xor-int", Fmt::F23x),
    ("shl-int", Fmt::F23x),
    ("shr-int", Fmt::F23x),
    ("ushr-int", Fmt::F23x),
    ("add-long", Fmt::F23x),
    ("sub-long", Fmt::F23x),
    ("mul-long", Fmt::F23x),
    ("div-long", Fmt::F23x),
    ("rem-long", Fmt::F23x),
    ("and-long", Fmt::F23x),
    ("or-long", Fmt::F23x),
    ("xor-long", Fmt::F23x),
    ("shl-long", Fmt::F23x),
    ("shr-long", Fmt::F23x),
    ("ushr-long", Fmt::F23x),
    ("add-float", Fmt::F23x),
    ("sub-float", Fmt::F23x),
    ("mul-float", Fmt::F23x),
    ("div-float", Fmt::F23x),
    ("rem-float", Fmt::F23x),
    ("add-double", Fmt::F23x),
    ("sub-double", Fmt::F23x),
    ("mul-double", Fmt::F23x),
    ("div-double", Fmt::F23x),
    ("rem-double", Fmt::F23x),
    ("add-int/2addr", Fmt::F12x),
    ("sub-int/2addr", Fmt::F12x),
    ("mul-int/2addr", Fmt::F12x),
    ("div-int/2addr", Fmt::F12x),
    ("rem-int/2addr", Fmt::F12x),
    ("and-int/2addr", Fmt::F12x),
    ("or-int/2addr", Fmt::F12x),
    ("xor-int/2addr", Fmt::F12x),
    ("shl-int/2addr", Fmt::F12x),
    ("shr-int/2addr", Fmt::F12x),
    ("ushr-int/2addr", Fmt::F12x),
    ("add-long/2addr", Fmt::F12x),
    ("sub-long/2addr", Fmt::F12x),
    ("mul-long/2addr", Fmt::F12x),
    ("div-long/2addr", Fmt::F12x),
    ("rem-long/2addr", Fmt::F12x),
    ("and-long/2addr", Fmt::F12x),
    ("or-long/2addr", Fmt::F12x),
    ("xor-long/2addr", Fmt::F12x),
    ("shl-long/2addr", Fmt::F12x),
    ("shr-long/2addr", Fmt::F12x),
    ("ushr-long/2addr", Fmt::F12x),
    ("add-float/2addr", Fmt::F12x),
    ("sub-float/2addr", Fmt::F12x),
    ("mul-float/2addr", Fmt::F12x),
    ("div-float/2addr", Fmt::F12x),
    ("rem-float/2addr", Fmt::F12x),
    ("add-double/2addr", Fmt::F12x),
    ("sub-double/2addr", Fmt::F12x),
    ("mul-double/2addr", Fmt::F12x),
    ("div-double/2addr", Fmt::F12x),
    ("rem-double/2addr", Fmt::F12x),
    ("add-int/lit16", Fmt::F22s),
    ("rsub-int", Fmt::F22s),
    ("mul-int/lit16", Fmt::F22s),
    ("div-int/lit16", Fmt::F22s),
    ("rem-int/lit16", Fmt::F22s),
    ("and-int/lit16", Fmt::F22s),
    ("or-int/lit16", Fmt::F22s),
    ("xor-int/lit16", Fmt::F22s),
    ("add-int/lit8", Fmt::F22b),
    ("rsub-int/lit8", Fmt::F22b),
    ("mul-int/lit8", Fmt::F22b),
    ("div-int/lit8", Fmt::F22b),
    ("rem-int/lit8", Fmt::F22b),
    ("and-int/lit8", Fmt::F22b),
    ("or-int/lit8", Fmt::F22b),
    ("xor-int/lit8", Fmt::F22b),
    ("shl-int/lit8", Fmt::F22b),
    ("shr-int/lit8", Fmt::F22b),
    ("ushr-int/lit8", Fmt::F22b),
    ("unused-e3", Fmt::None),
    ("unused-e4", Fmt::None),
    ("unused-e5", Fmt::None),
    ("unused-e6", Fmt::None),
    ("unused-e7", Fmt::None),
    ("unused-e8", Fmt::None),
    ("unused-e9", Fmt::None),
    ("unused-ea", Fmt::None),
    ("unused-eb", Fmt::None),
    ("unused-ec", Fmt::None),
    ("unused-ed", Fmt::None),
    ("unused-ee", Fmt::None),
    ("unused-ef", Fmt::None),
    ("unused-f0", Fmt::None),
    ("unused-f1", Fmt::None),
    ("unused-f2", Fmt::None),
    ("unused-f3", Fmt::None),
    ("unused-f4", Fmt::None),
    ("unused-f5", Fmt::None),
    ("unused-f6", Fmt::None),
    ("unused-f7", Fmt::None),
    ("invoke-polymorphic", Fmt::F45cc),
    ("invoke-polymorphic/range", Fmt::F4rcc),
    ("invoke-custom", Fmt::F35c),
    ("invoke-custom/range", Fmt::F3rc),
    ("const-method-handle", Fmt::F21c),
    ("const-method-type", Fmt::F21c),
    ("unused-fe", Fmt::None),
    ("unused-ff", Fmt::None),
];

/// invocation kind for invoke-* opcodes
pub fn invoke_kind(opcode: u8) -> Option<&'static str> {
    match opcode {
        0x6e | 0x74 => Some("virtual"),
        0x6f | 0x75 => Some("super"),
        0x70 | 0x76 => Some("direct"),
        0x71 | 0x77 => Some("static"),
        0x72 | 0x78 => Some("interface"),
        0xf8 | 0xf9 => Some("polymorphic"),
        0xfa | 0xfb => Some("custom"),
        _ => None,
    }
}

/// field access kind for *get/*put opcodes
pub fn access_kind(opcode: u8) -> Option<&'static str> {
    match opcode {
        0x52..=0x5f => Some("instance"),
        0x60..=0x6d => Some("static"),
        _ => None,
    }
}
