name: Build and Distribute jiap_core

on:
  push:
    branches: [ main ]
    paths:
      - 'jiap_core/**'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'jiap_core/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Generate version number
      id: version
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if present for version number
          VERSION=${VERSION#v}
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          VERSION="pr-${{ github.event.number }}-${GITHUB_SHA::7}"
        else
          VERSION="main-${GITHUB_SHA::7}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: jiap_core

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: jiap_core
      env:
        VERSION: ${{ env.VERSION }}

    - name: Run tests
      run: ./gradlew test
      working-directory: jiap_core

    - name: Create distribution
      run: ./gradlew dist
      working-directory: jiap_core
      env:
        VERSION: ${{ env.VERSION }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jiap-core-distribution
        path: |
          jiap_core/build/dist/*.jar
          jiap_core/build/libs/*.jar
        retention-days: 30

    - name: Upload to GitHub Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          jiap_core/build/dist/*.jar
          jiap_core/build/libs/*.jar
        name: Release ${{ env.VERSION }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}